mysql:
  image: mysql:8.0
  storage: 5Gi
  rootPassword: root
  database: travelmanagement

backend:
  image: akhilreddy9/travelmanagement-backend:v1
  replicas: 2
  port: 8080
  nodePort: 30083

frontend:
  image: akhilreddy9/travelmanagement-frontend:v1
  replicas: 2
  port: 8080
  nodePort: 30082

ingress:
  enabled: true
  host: travelmanagement.local

autoscaling:
  backend:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60

  frontend:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
